//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressTable
    {
        public int UserAddressID { get; set; }
        public int UserID { get; set; }
        public int AddressTypeID { get; set; }
        public string FullAddress { get; set; }
        public int VisibleStatusID { get; set; }
        public int CreatedBy_UserID { get; set; }
    
        public virtual AddressTypeTable AddressTypeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual VisibleStatusTable VisibleStatusTable { get; set; }
    }
}
